### ISSUE TITLE
Queue song as the next song

### ISSUE THREAD

**Issue by e-gloo** [robinfriedli/aiode#193]
Hey,

This is a feature in Spotify, when a playlist is currently playing, you can add a song outside the playlist in the queue, and it is added as the next song, in a new "temporary" or a "sub" queue. Once this sub queue is over, it goes back to the playlist where it left. With this, the outside song is just played once and it is not part of the playlist.

If that sub queue might be too complex, maybe just add a song as the next song in queue, or at index after the current song. Just like the `!insert` command for local playlist
Ex:
- `!queue !next {song}` => adds the song as the next song in the queue
- `!queue !insert 1 {song}` => same as the previous command, adds the song one place after the current one
- `!queue !insert 2 {song}` => adds the song two songs later after the current one

Anyway, just a feature suggestion :smiley_cat:

**Comment by robinfriedli** [comment]
Better queue management is already on the list for botify 2 and inserting tracks anywhere in the queue is certainly amongst the planned improvements 😉
