### ISSUE TITLE
Not really a issue but a question.

### ISSUE THREAD

**Issue by Edison12300** [robinfriedli/aiode#252]
Sorry for asking here, but I don't know any other to contact you. I tried to clone the repository and made my bot for my server, and I'm curios that is there a way to make the bot stay in the voice channel, even if no people is in it. It will pause when all people left the voice chat and start playing music again when one enters. Is there a way to add to the current codes to make this happen?

**Comment by robinfriedli** [comment]
You could disable auto pause using the property command but the bot would still leave after being alone for an hour when the audio playback is cleanup up but you could disable audio playback cleanup by removing the PlaybackCleanupTask from cronJobs.xml. However, audio would not pause / unpause when people leave. For that it would probably be easiest to modify VoiceChannelListener by simply removing `playback.leaveChannel();` from `onGuildVoiceLeave` and expand `onGuildVoiceJoin` to unpause playback if paused and previously alone.
