### ISSUE TITLE
No replies from the botify

### ISSUE THREAD

**Issue by Coder-Vasen** [robinfriedli/aiode#268]
Botify bot is great. I love it. At first it worked great. But suddenly botify stopped to reply to command given
Like $botify help doesn't show
![Capture](https://user-images.githubusercontent.com/69237691/141683193-6972212d-e29d-4159-8c0c-85c864771e3d.PNG)
But it plays the song and resume all the command are working, but we couldn't able to get the reply

**Comment by robinfriedli** [comment]
I presume this is in regards to the public instance? This issue tracker is meant for issues with botify in general, not specific to the public bot instance. Please join the [support server](https://discord.com/invite/gdc25AG) for that instead. Furthermore, I can't reproduce the issue, probably just a temporary rate limit.
