### ISSUE TITLE
Allow setting the default volume

### ISSUE THREAD

**Issue by SwiftWinds** [robinfriedli/aiode#306]
Often, the music bot is too loud at first and I set the volume to 10 each time. Having it as 10% as default would be nice! I know that you can change the default volume for yourself but that doesn't change others' settings and new users would get blasted with the loud music the first time they joined.

**Comment by DigitallyFidget** [comment]
I wish that was default, I run the bot myself and defaulted it to 10% from source, because everyone always complained the thing was way too loud and would just mute the thing.

**Comment by SwiftWinds** [comment]
This was completed? Is there a newly added command to set the default volume? I don't see it in yesterday's commit.

**Comment by robinfriedli** [comment]
The default volume can be set using the property command, this has been completed a while ago

**Comment by SwiftWinds** [comment]
Ahh ok thank you so much (:
