### ISSUE TITLE
enable "message content" for "custom prefixes "?

### ISSUE THREAD

**Issue by weeedy** [robinfriedli/aiode#331]
![image](https://user-images.githubusercontent.com/20976962/193465101-0f55177f-3ff2-4bb1-8846-5d593d26b920.png)

Hello, is it possible, to enable "message content" on discord server? Or did discord removed this function? I saw some other bots, still working with "old/custom prefix" style, instead of /.

And one "side question" - did you close your aiode support/test discord server? 

Thank you for your great work and greetings !
Leo

**Comment by robinfriedli** [comment]
Message content isn't something that is enabled per guild (aka server) but per bot account. The only way to enable message content is either by being a small unverified bot (< 100 guilds), getting approved for message content by Discord (requires a good reason / use case, Discord has declined my request) or temporarly enable it anyway but this stops the bot from being added to new guilds and was only available for a limited time (iirc only until October)

> And one "side question" - did you close your aiode support/test discord server

No, I haven't https://discord.gg/k8uPrqck

**Comment by weeedy** [comment]
Thank you for your fast response! 🙏
