### ISSUE TITLE
Private Bot is Offline

### ISSUE THREAD

**Issue by PatchAlchemist** [robinfriedli/aiode#336]
I followed every step in the readme and have my bot successfully running in the terminal "All starters done".

The bot has been invited to my server but it's still offline and unresponsive.

Is there a step missing in the readme? I assumed that finishing all of step 6 would've resulted in the bot coming online

**Comment by PatchAlchemist** [comment]
So I found where the ERROR was occurring after looking at this thread: https://github.com/robinfriedli/aiode/issues/136#issuecomment-686461503

Every line works for me except for JDA - Finished Loading!
Instead of that I get this error:

[1;31mERROR←[0;39m 2023-02-14 13:14:22,886 [←[34mJDA [0 / 1] MainWS-WriteThread←[0;39m] ←[33mnet.dv8tion.jda.internal.requests.WebSocketClient←[0;39m: WebSocket connection was closed and cannot be recovered due to identification issues
CloseCode(4014 / Disallowed intents. Your bot might not be eligible to request a privileged intent such as GUILD_PRESENCES, MESSAGE_CONTENT, or GUILD_MEMBERS.)

**Comment by PatchAlchemist** [comment]
I don't fully understand URI callbacks and I'm assuming it has something to do with that, but I set my Spotify app and Discord app's URI callbacks to my public IP and portforwarded to my PC, and tried reformatting the domain a bunch of times (no end slash, with an end slash, port specified, no port specified)

I really don't know what I'm doing wrong

**Comment by robinfriedli** [comment]
Looks like you have text commands enabled (`aiode.preferences.enable_message_content`) but your bot user is not opted into the message content intent. Make sure its enabled on your discord developer dashboard. This is usually not an issue for self-hosters because privileged gateway intents can always be enabled as long as the bot user is in 100 servers or fewer.

**Comment by PatchAlchemist** [comment]
That worked! Thanks alot!
