### ISSUE TITLE
How to implement an auto-queueing script?

### ISSUE THREAD

**Issue by ProfLS** [robinfriedli/aiode#337]
(Preface: I have set my prefix to `=` instead of `$aiode`, and my argument prefix is `-` instead of `$`)

I wanted to make a script which checks there are any songs in the queue before executing a play command.  On my server, we often have a massive queue, which accidentally gets wiped.  Thus, I decided to implement an "Auto Queue" function in case there is anything in the queue.  Here was the script:
```
if (command.getIdentifier().equals('play') && !playback.audioQueue.isEmpty()) {
    command.run('queue ' + command.getCommandBody())
    command.abort()
}
```

I then tried to implement it through the following commands:
```
=script -identifier='playAsQueue' 
"if (command.getIdentifier().equals('play') && !playback.audioQueue.isEmpty()) {
    command.run('queue ' + command.getCommandBody())
    command.abort()
}"
```

then I ran the `=script` command to check my script was active, which it was.

However, upon testing it by queueing a bunch of songs and running the play command, nothing happened.  How do I correctly implement the script?  Is there any specific method to have the script be continuously running?

Any help is appreciated!

**Comment by robinfriedli** [comment]
Scripts are custom commands that run when prompted. To use this script you'd have to use the `playAsQueue` command instead of play and remove the `command.getIdentifier().equals('play')`. You probably meant to use the interceptor command instead, which creates scripts that are executed before a command runs.

**Comment by ProfLS** [comment]
Yup!  That's what I intended, thank you for the clarification :)
