### ISSUE TITLE
Changing Discord theme resets bot volume back to 100%

### ISSUE THREAD

**Issue by URoulon** [robinfriedli/aiode#339]
If you happen to have Nitro, give this a try.
Changing your theme in the settings sets the bot's volume back to 100% from whatever value it previously was at.

Running Ptb 183897 (585e2cd), Host 1.0.1026 (30853)

**Comment by URoulon** [comment]
Muting a stream also has the same effect.

**Comment by robinfriedli** [comment]
I'm assuming you're talking about the user volume set via discord, not the volume command? That has nothing to do with the bot. If anything it's a discord issue.
