### ISSUE TITLE
WebSocket permissions issue?

### ISSUE THREAD

**Issue by MikeTodd** [robinfriedli/aiode#344]
This is when self-hosting, under Windows 11 64 bit. I'm not using a local web server (just need the basic functionality) so I skipped that part of the install. I'm getting the following error when I start up the JAR:

```
ERROR 2023-06-01 10:53:40,060 [JDA [0 / 1] MainWS-WriteThread] net.dv8tion.jda.internal.requests.WebSocketClient: WebSocket connection was closed and cannot be recovered due to identification issues
CloseCode[DISALLOWED_INTENTS](code=4014, meaning=Disallowed intents. Your bot might not be eligible to request a privileged intent such as GUILD_PRESENCES, MESSAGE_CONTENT, or GUILD_MEMBERS.)
```

Before that, I received these warnings, which might be related:

```
WARN  2023-06-01 10:53:39,278 [main] net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder: Automatically disabled CacheFlags due to missing intents
WARN  2023-06-01 10:53:39,280 [main] java.util.stream.ForEachOps$ForEachOp$OfRef: Disabled CacheFlag.SCHEDULED_EVENTS (missing GatewayIntent.SCHEDULED_EVENTS)
WARN  2023-06-01 10:53:39,281 [main] net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder: You can manually disable these flags to remove this warning by using disableCache(CacheFlag.SCHEDULED_EVENTS) on your DefaultShardManagerBuilder
```

What should I do to resolve this issue, or does it even matter? The bot seems to have started successfully otherwise with a final message of `net.robinfriedli.aiode.boot.SpringBootstrap: All starters done` and though the bot is in my server, it doesn't respond to `/play` or any other slash command.

**Comment by robinfriedli** [comment]
Sounds like you have message content enabled (`aiode.preferences.enable_message_content`) but didn't request access to the corresponding privileged gateway intent. As long as your bot is in fewer than 100 guilds it's as simple as enabling the setting through the discord developer dashboard (there should be a toggle somewhere to enable message content for your application). Else you need to go through a whole verification process. Having message content enabled means you can use traditional text commands that start with a prefix, else you're limited to pinging the bot or using slash commands (wouldn't recommend the latter).

**Comment by MikeTodd** [comment]
Awesome, that was it exactly! Closing this out, and thank you! :)
