### ISSUE TITLE
Album title tracks play the first track of the album instead (Spotify)

### ISSUE THREAD

**Issue by cgreely** [robinfriedli/aiode#351]
When playing the title track of an album from Spotify (album has the same name as track), instead the first track of the album will play instead. Tested with a few different songs and it happens each time. Happens regardless of whether it is played through a link or with a search.

**Comment by robinfriedli** [comment]
You sure you aren't just playing the album and have repeat $one enabled or something? Because that makes no sense and I couldn't reproduce it with One More Light by Linkin Park, Californication by Red Hot Chilli Peppers, American Idiot by Green Day or Ocean Avenue by Yellowcard.

**Comment by cgreely** [comment]
Repeat is disabled, tried it again and its still happening

**Comment by robinfriedli** [comment]
Yeah I can't help you without additional information. The issue you're describing doesn't make any sense (the album is irrelevant when searching a track unless you explicitly use the `album:` filter) so there's no way it matters if it has the same name as the track. The only way this makes sense is if the `searchTracks` function of the Spotify API is broken, which is extremely unlikely, and it's not reproducible with any of my examples, so clearly it's something else. You're gonna have to provide some actual examples or screenshots.
