### ISSUE TITLE
auto queue

### ISSUE THREAD

**Issue by Klayrex** [robinfriedli/aiode#375]
auto queue
Added the 'auto queue' guild property to control the behaviour of the bot when using the play command while already playing something else. This is accessible via the property command with the following options: 'queue next' -> insert the tracks into the queue after the current track, this is now the default / 'queue last' -> append the tracks to the end of the queue / 'off' -> enables the original behaviour the play command replaces the current queue

Please tell me how to 'off' auto queue
What is property command
Commands like:

/play input:off
/play off   or  /play 'off'
/off play   or  /'off' play
off /play    or  'off' /play 

They do not work

**Comment by robinfriedli** [comment]
Why are you using the play command? Obviously that plays a track called "off". Just use the help command and it will tell you exactly what to type, in that case

`@aiode property auto queue $set off`

And don't use slash commands, they suck (slash command would be `/property input:auto queue set:off`.

**Comment by Klayrex** [comment]
Thanks a lot
It's still the best music bot for discord so far
