### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by fartboygh** [robinfriedli/aiode#382]
Gives you message

Could not load track 
Message returned by source: Video returned by YouTube isn't what was requested

**Comment by valve-developer** [comment]
spotify links, youtube links all give:

Message returned by source: Video returned by YouTube isn't what was requested

**Comment by Daichi-Tsukiji** [comment]
Also having issues here. Youtube and spotify are now longer usable, after working perfectly for so long.

**Comment by ProfLS** [comment]
Same here, Imma do some testing on my end and see what's up, then update here if I have any luck

**Comment by robinfriedli** [comment]
It's a known lavaplayer  that is already tracked here in the lavalink repo: https://github.com/lavalink-devs/Lavalink/issues/1030

Not sure if there is a snapshot dependency with a possible fix out there already

**Comment by robinfriedli** [comment]
https://github.com/lavalink-devs/lavaplayer/pull/88 there's an open PR with a fix, not merged yet
