### ISSUE TITLE
Project fails to build due to missing dependency jda-nas:1.1.0

### ISSUE THREAD

**Issue by tdsotm** [robinfriedli/aiode#406]
I tried to build the project in order to self host the bot but the build fails with:
`Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.sedmelluq:jda-nas:1.1.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/sedmelluq/jda-nas/e41b8fedb5/jda-nas-e41b8fedb5.pom
       - https://jcenter.bintray.com/com/github/sedmelluq/jda-nas/e41b8fedb5/jda-nas-e41b8fedb5.pom
       - https://repo.jenkins-ci.org/releases/com/github/sedmelluq/jda-nas/e41b8fedb5/jda-nas-e41b8fedb5.pom
       - https://m2.dv8tion.net/releases/com/github/sedmelluq/jda-nas/e41b8fedb5/jda-nas-e41b8fedb5.pom
       - https://maven.lavalink.dev/snapshots/com/github/sedmelluq/jda-nas/e41b8fedb5/jda-nas-e41b8fedb5.pom
       - https://maven.lavalink.dev/releases/com/github/sedmelluq/jda-nas/e41b8fedb5/jda-nas-e41b8fedb5.pom
     Required by:
         project :
`

I've tried searching for the jar but couldn't get a hold of it. Can the library be provided in a local folder of the project?

**Comment by robinfriedli** [comment]
Since commit https://github.com/MinnDevelopment/udpqueue.rs/commit/f54ad343ade65d537c14627a34fcc1e53455027f got rid of the jda-nas requirement, I will be switching to udpqueue
